from __future__ import annotations

from typing import Any

__backend__: str

def e_step(
    X: Any,
    weights: Any,
    means: Any,
    prec_chol: Any,
    log_det_half: Any,
    log_prob: Any,
    resp: Any,
    ll_per_cell: Any,
    *,
    n: int,
    d: int,
    K: int,
    stream: int = 0,
) -> None: ...
def e_step_cublas(
    X: Any,
    weights: Any,
    means: Any,
    prec_chol: Any,
    log_det_half: Any,
    centered_workspace: Any,
    y_workspace: Any,
    log_prob: Any,
    resp: Any,
    ll_per_cell: Any,
    *,
    n: int,
    d: int,
    K: int,
    stream: int = 0,
    handle: int,
) -> None: ...
def m_step(
    resp: Any,
    X: Any,
    ones: Any,
    weights: Any,
    means: Any,
    covariances: Any,
    N_k_workspace: Any,
    num_workspace: Any,
    centered_workspace: Any,
    *,
    n: int,
    d: int,
    K: int,
    reg_covar: float,
    stream: int = 0,
    handle: int,
) -> None: ...
def precision_cholesky_full(
    cov_work: Any,
    prec_chol: Any,
    log_det: Any,
    dev_info: Any,
    *,
    dA: int,
    dB: int,
    d: int,
    K: int,
    stream: int = 0,
    cublas_handle: int,
    cusolver_handle: int,
) -> None: ...
def spherical_gmm_fit_batched(
    pvec: Any,
    offsets: Any,
    m0: Any,
    v0: Any,
    m1_init: Any,
    v1_init: Any,
    resp1: Any,
    m1_out: Any,
    v1_out: Any,
    w1_out: Any,
    *,
    n_genes: int,
    max_iter: int,
    tol: float,
    reg_covar: float,
    stream: int = 0,
) -> None: ...
def mixscape_project_em(
    dat: Any,
    dat_offsets: Any,
    n_per_gene: Any,
    k_per_gene: Any,
    cell_offsets: Any,
    feat_offsets: Any,
    nt_cells_mean: Any,
    guide_sel: Any,
    nt_in_all: Any,
    active_genes: Any,
    pvec_scratch: Any,
    resp1: Any,
    *,
    n_active: int,
    max_k: int,
    max_iter: int,
    tol: float,
    reg_covar: float,
    stream: int = 0,
) -> None: ...
