from __future__ import annotations

from typing import Any

__backend__: str

def clustering_loop(
    Z_norm: Any,
    *,
    R: Any,
    E: Any,
    O: Any,
    Pr_b: Any,
    cats: Any,
    theta: Any,
    joint_codes: Any | None = None,
    marginal_joint_offsets: Any | None = None,
    marginal_joint_indices: Any | None = None,
    O_joint: Any | None = None,
    Y: Any,
    Y_norm: Any,
    similarities: Any,
    idx_list: Any,
    idx_list_alt: Any,
    sort_keys: Any,
    sort_keys_alt: Any,
    cub_temp: Any,
    R_out_buffer: Any,
    cats_in: Any,
    joint_codes_in: Any | None = None,
    R_in_sum: Any,
    R_out_sum: Any,
    penalty: Any,
    obj_scalar: Any,
    ones_vec: Any,
    last_obj: Any,
    n_cells: int,
    n_pcs: int,
    n_clusters: int,
    n_batches: int,
    n_covariates: int,
    n_joint_categories: int,
    block_size: int,
    colsum_algo: int,
    sigma: float,
    tol: float,
    max_iter: int,
    seed: int,
    stabilized: bool,
    use_joint_scatter: bool,
    stream: int = 0,
    handle: int,
) -> None: ...
def compute_objective(
    R: Any,
    *,
    similarities: Any,
    O: Any,
    E: Any,
    theta: Any,
    sigma: float,
    obj_scalar: Any,
    n_cells: int,
    n_clusters: int,
    n_batches: int,
    stabilized: bool,
    stream: int = 0,
) -> float: ...
def get_cub_sort_temp_bytes(
    *,
    n_cells: int,
) -> int: ...
