from __future__ import annotations

from typing import Any

__backend__: str

def correction_batched(
    X: Any,
    *,
    R: Any,
    O: Any,
    cats: Any,
    cat_offsets: Any,
    cell_indices: Any,
    lambda_kb: Any,
    n_cells: int,
    n_pcs: int,
    n_clusters: int,
    n_batches: int,
    Z: Any,
    inv_mats: Any,
    Phi_t_diag_R_X_all: Any,
    W_all: Any,
    g_factor: Any,
    g_P_row0: Any,
    X_batch: Any,
    R_batch: Any,
    batch_chunk_size: int,
    stream: int = 0,
    handle: int,
) -> None: ...
def prepare_multi(
    X: Any,
    *,
    R: Any,
    O: Any,
    joint_codes: Any,
    joint_cats: Any,
    joint_offsets: Any,
    joint_cell_indices: Any,
    marginal_joint_offsets: Any,
    marginal_joint_indices: Any,
    lambda_kb: Any,
    active_mask: Any,
    n_cells: int,
    n_pcs: int,
    n_clusters: int,
    n_batches: int,
    n_covariates: int,
    n_joint_categories: int,
    gram: Any,
    rhs: Any,
    joint_O: Any,
    joint_rhs: Any,
    stream: int = 0,
    handle: int,
) -> None: ...
def apply_multi(
    X: Any,
    *,
    R: Any,
    W_all: Any,
    cats: Any,
    n_cells: int,
    n_pcs: int,
    n_clusters: int,
    n_batches: int,
    n_covariates: int,
    initialize_output: bool,
    Z: Any,
    stream: int = 0,
) -> None: ...
