"""Bounded host streaming reductions implemented by the Rust backend."""

from typing import Any

def _set_host_worker_limit(limit: int) -> int: ...
def aggr_csr_host(
    data: Any,
    indices: Any,
    indptr: Any,
    cats: Any,
    *,
    out_sum: Any = None,
    out_count: Any = None,
    out_sqsum: Any = None,
    mask: Any = None,
    n_cells: int,
    n_genes: int,
    sub_batch_rows: int = 4096,
) -> None: ...
def aggr_csc_host(
    data: Any,
    indices: Any,
    indptr: Any,
    cats: Any,
    *,
    out_sum: Any = None,
    out_count: Any = None,
    out_sqsum: Any = None,
    mask: Any = None,
    n_cells: int,
    n_genes: int,
    sub_batch_cols: int = 4096,
) -> None: ...
def aggr_dense_host(
    X: Any,
    cats: Any,
    *,
    out_sum: Any = None,
    out_count: Any = None,
    out_sqsum: Any = None,
    mask: Any = None,
    sub_batch: int = 4096,
) -> None: ...
def hist_csr_host(
    data: Any,
    indices: Any,
    indptr: Any,
    gcodes: Any,
    hist: Any,
    *,
    group_sums: Any = None,
    group_nnz: Any = None,
    n_cells: int,
    n_genes: int,
    n_groups: int,
    n_bins: int,
    bin_low: float,
    inv_bin_width: float,
    col_start: int = 0,
    col_stop: int = -1,
    sub_batch_rows: int = 4096,
) -> None: ...
def hist_csc_host(
    data: Any,
    indices: Any,
    indptr: Any,
    gcodes: Any,
    hist: Any,
    *,
    group_sums: Any = None,
    group_nnz: Any = None,
    n_cells: int,
    n_genes: int,
    n_groups: int,
    n_bins: int,
    bin_low: float,
    inv_bin_width: float,
    col_start: int,
    col_stop: int,
    sub_batch_cols: int = 4096,
) -> None: ...
def hist_dense_host(
    X: Any,
    gcodes: Any,
    hist: Any,
    *,
    group_sums: Any = None,
    group_nnz: Any = None,
    n_groups: int,
    n_bins: int,
    bin_low: float,
    inv_bin_width: float,
    col_start: int,
    col_stop: int,
    sub_batch_cols: int = 4096,
) -> None: ...
