# Embed the Harmony cuTile kernels (bfloat16 assignments) when the CUDA toolkit
# is 13.0+ and `cuda.tile` is importable; otherwise Harmony uses float32 only.
#
# rsc_harmony_cutile(<targets>...) exports one cubin per kernel and GPU
# architecture, embeds them with bin2c and defines RSC_CUTILE_ENABLED=1 on the
# targets. Nothing is required at runtime beyond the CUDA 13 runtime.

option(RSC_BUILD_CUTILE "Embed cuTile kernels for Harmony dtype='bfloat16'" ON)

set(_RSC_CUTILE_DIR "${PROJECT_SOURCE_DIR}/src/rapids_singlecell/_cuda/harmony/cutile")
set(_RSC_CUTILE_SYMBOLS
    rsc_harmony_rtz_large_d64 rsc_harmony_rtz_small_d64 rsc_harmony_neg_rw_d64
    rsc_harmony_rtz_large_d128 rsc_harmony_rtz_small_d128 rsc_harmony_neg_rw_d128)
# Architectures tileiras targets.
set(_RSC_CUTILE_ARCHS 80 86 87 88 89 90 100 103 107 110 120 121)

# rsc_harmony_cutile(<target> <symbol>...) embeds the listed kernels (all
# exported PC widths) for every selected architecture into <target>.
function(rsc_harmony_cutile target)
  if(NOT RSC_BUILD_CUTILE OR CUDAToolkit_VERSION VERSION_LESS 13.0)
    message(STATUS "Harmony cuTile kernels: off (needs CUDA 13.0+, found ${CUDAToolkit_VERSION})")
    return()
  endif()
  execute_process(
    COMMAND "${Python_EXECUTABLE}" -c "import cuda.tile"
    RESULT_VARIABLE _import ERROR_QUIET OUTPUT_QUIET)
  find_program(_RSC_BIN2C bin2c PATHS "${CUDAToolkit_BIN_DIR}" NO_DEFAULT_PATH)
  if(NOT _import EQUAL 0 OR NOT _RSC_BIN2C)
    message(STATUS "Harmony cuTile kernels: off (needs `cuda.tile` in ${Python_EXECUTABLE} and bin2c)")
    return()
  endif()

  set(_archs "${CMAKE_CUDA_ARCHITECTURES}")
  if(_archs STREQUAL "native")
    set(_archs "${CMAKE_CUDA_ARCHITECTURES_NATIVE}")
  endif()
  set(_selected "")
  foreach(_arch IN LISTS _archs)
    string(REGEX MATCH "^[0-9]+" _cc "${_arch}")
    if(_cc IN_LIST _RSC_CUTILE_ARCHS AND NOT _cc IN_LIST _selected)
      list(APPEND _selected ${_cc})
    endif()
  endforeach()
  if(NOT _selected)
    message(STATUS "Harmony cuTile kernels: off (no sm_80+ target in '${_archs}')")
    return()
  endif()

  set(_out "${CMAKE_CURRENT_BINARY_DIR}/harmony_cutile")
  file(MAKE_DIRECTORY "${_out}/${target}")
  set(_headers "")
  set(_includes "")
  set(_entries "")
  foreach(_cc IN LISTS _selected)
    # One export per architecture writes every kernel; shared by all targets.
    set(_cubins "")
    foreach(_sym IN LISTS _RSC_CUTILE_SYMBOLS)
      list(APPEND _cubins "${_out}/${_sym}_sm_${_cc}.cubin")
    endforeach()
    if(NOT TARGET harmony_cutile_export_sm_${_cc})
      add_custom_command(
        OUTPUT ${_cubins}
        COMMAND "${Python_EXECUTABLE}" "${_RSC_CUTILE_DIR}/export_harmony_tile.py" "${_out}" sm_${_cc}
        DEPENDS "${_RSC_CUTILE_DIR}/export_harmony_tile.py" "${_RSC_CUTILE_DIR}/harmony_tile.py"
        COMMENT "Exporting Harmony cuTile kernels for sm_${_cc}"
        VERBATIM)
      add_custom_target(harmony_cutile_export_sm_${_cc} DEPENDS ${_cubins})
    endif()
    foreach(_sym IN LISTS ARGN)
      foreach(_width 64 128)
        set(_name "${_sym}_d${_width}_sm_${_cc}")
        set(_header "${_out}/${target}/${_name}.h")
        add_custom_command(
          OUTPUT "${_header}"
          COMMAND "${_RSC_BIN2C}" --const --static --name ${_name} "${_out}/${_name}.cubin" >
                  "${_header}"
          DEPENDS harmony_cutile_export_sm_${_cc} "${_out}/${_name}.cubin"
          VERBATIM)
        list(APPEND _headers "${_header}")
        string(APPEND _includes "#include \"${_name}.h\"\n")
        math(EXPR _major "${_cc} / 10")
        math(EXPR _minor "${_cc} % 10")
        string(APPEND _entries
               "    {${_major}, ${_minor}, \"${_sym}_d${_width}\", ${_name}, sizeof(${_name})},\n")
      endforeach()
    endforeach()
  endforeach()
  file(CONFIGURE OUTPUT "${_out}/${target}/harmony_cutile_cubins.h" CONTENT
"#pragma once
// Generated by cmake/harmony_cutile.cmake.
#include <cstddef>
@_includes@
struct HarmonyCutileCubin {
    int cc_major, cc_minor;
    const char* symbol;
    const unsigned char* data;
    size_t size;
};
static const HarmonyCutileCubin kHarmonyCutileCubins[] = {
@_entries@};
" @ONLY)
  add_custom_target(${target}_cutile DEPENDS ${_headers})
  add_dependencies(${target} ${target}_cutile)
  target_include_directories(${target} PRIVATE "${_out}/${target}")
  target_compile_definitions(${target} PRIVATE RSC_CUTILE_ENABLED=1)
  message(STATUS "Harmony cuTile kernels for ${target}: sm_${_selected}")
endfunction()
